In [1]:
import numpy as np
from tensorflow import keras

In [4]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
reviews=['nice food', 'amazing restaurant', 'too good', 'just loved it!', 'will go again', 'horrible food', 'never go there', 'poor service', 'poor quality', 'needs improvement']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
len(reviews)

10

In [7]:
len(sentiment)

10

In [8]:
keras.preprocessing.text.one_hot('amazing restaurant', 30)

[6, 29]

In [9]:
vocab_size=30
encoded_reviews= [keras.preprocessing.text.one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[4, 26],
 [6, 29],
 [5, 7],
 [23, 19, 5],
 [19, 18, 9],
 [23, 26],
 [27, 18, 26],
 [5, 2],
 [5, 24],
 [10, 18]]

In [10]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews, maxlen=max_length, padding = 'post')
padded_reviews

array([[ 4, 26,  0,  0],
       [ 6, 29,  0,  0],
       [ 5,  7,  0,  0],
       [23, 19,  5,  0],
       [19, 18,  9,  0],
       [23, 26,  0,  0],
       [27, 18, 26,  0],
       [ 5,  2,  0,  0],
       [ 5, 24,  0,  0],
       [10, 18,  0,  0]], dtype=int32)

In [12]:
embeddded_vector_size=5
model= keras.models.Sequential([
    keras.layers.Embedding(vocab_size, embeddded_vector_size, input_length=max_length, name='embedding'),
    keras.layers.Flatten(),
    keras.layers.Dense(1, activation='sigmoid')
])

In [13]:
X=padded_reviews
y=sentiment

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X, y, epochs=100, verbose=0)

In [16]:
loss, accuracy = model.evaluate(X, y)
print(loss, accuracy)

1/1 [==============================] - 0s 127ms/step - loss: 0.5369 - accuracy: 1.0000
0.5369173288345337 1.0


In [21]:
weights= model.get_layer('embedding').get_weights()[0]

In [22]:
weights

array([[-0.14660808,  0.08730857, -0.11524427, -0.12581368, -0.14487101],
       [-0.01528693, -0.01761051, -0.02862369, -0.02480046, -0.02614037],
       [ 0.05049315,  0.13857953, -0.14211448, -0.10771593, -0.12223296],
       [-0.04857203, -0.03647683, -0.04573325, -0.00100482, -0.01185298],
       [-0.11713532, -0.13859773, -0.13351412,  0.10557751, -0.08956879],
       [ 0.1270716 , -0.06504076,  0.08927894,  0.15598519,  0.12544647],
       [-0.05183703, -0.05731012, -0.11709302,  0.11593632, -0.12756678],
       [-0.09832291, -0.1326517 ,  0.08534854,  0.09052283,  0.05574093],
       [ 0.01500168,  0.02614314, -0.03500504, -0.00887041,  0.01704103],
       [ 0.09524421, -0.12661767,  0.05397592,  0.11981714,  0.0976602 ],
       [ 0.09758956,  0.0981978 ,  0.06177233, -0.12462009,  0.13203152],
       [-0.02829951,  0.03372714, -0.04247186,  0.04229258, -0.03896995],
       [ 0.01713269, -0.04610524, -0.0355435 ,  0.01660724,  0.01772458],
       [-0.03873898, -0.027135  ,  0.0

In [23]:
weights[19]

array([-0.07580331, -0.05777595, -0.13014778,  0.07867623, -0.14239743],
      dtype=float32)